# source 'https://rubygems.org'
source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'thor'
gem 'selenium-webdriver'
gem 'rspec-expectations'
gem 'gherkin'
gem 'watir-webdriver'
gem 'page-object'
gem 'allure-cucumber', '~> 0.5.5'
gem 'allure-ruby-adaptor-api'
gem 'data_magic'
gem 'fig_newton'
gem 'headless'
gem 'faker'
gem 'pry-rails'
gem 'pry'
gem 'rubocop'
gem 'phantomjs'
gem 'json_spec', '~> 1.1.4'
gem 'rack-test'
gem 'cucumber-api-steps'
gem 'rest-client'
gem 'sinatra'
gem 'cucumber_statistics'
gem 'parallel_tests'
gem 'nokogiri'
gem 'sqlite3'
gem 'tzinfo-data'
gem 'bigdecimal'
gem 'watir-scroll'
gem 'ruby-duration'
gem 'chronic_duration'